### ISSUE TITLE
Square peg, round hole problem

### ISSUE THREAD

**Issue by andisa01** [andisa01/finalproject#1]
Hi Casey,

I mentioned this in an email to you earlier, but also flagging it here.
Given the paper we read today and the complete lack of signal in my initial tree, I'm realizing that my data are probably just not suited to phylogenetic analysis. I hadn't realized going in that the models for reconstructing phylogenies make assumptions about interbreeding that break down for population scale data.

Not really sure if I should just scrap my data and try with others?

**Comment by lemellenthin** [comment]
Hey Andis,

Just checking in here, did you still want to discuss data/methods? Did you end up figuring something out that works well for your goals?

Let me know, I would be happy to chat!

**Comment by andisa01** [comment]
Hi Lauren,
All sorted. No worries.
